version: 0.1

environment_variables:
    plaintext:
        MY_ACCOUNT_ID: "923361366103"
        BIG3_API_REPO_NAME: "3big-api-srv"
        BIG3_API_IMAGE_TAG: "latest"
        DOCKER_USERNAME: "aleistervm"
        DOCKER_TOKEN: "dckr_pat_j3Zd2d-1YlKey0tn6v1XsIacB9k"
        AWS_REGION: "us-east-1"
phases:
    pre_build:
        commands:
            - echo Logging in to Amazon  ECR...
            - echo $MY_ACCOUNT_ID
            - echo $AWS_REGION
            - echo $BIG3_API_REPO_NAME
            - echo $BIG3_API_IMAGE_TAG
            - echo $DOCKER_USERNAME
            - echo $DOCKER_TOKEN
            - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $MY_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
            # - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 341641179033.dkr.ecr.us-east-1.amazonaws.com
            # - docker login --username $DOCKER_USERNAME --password $DOCKER_TOKEN
            # - docker login --username aleistervm --password dckr_pat_j3Zd2d-1YlKey0tn6v1XsIacB9k
    build:
        commands:
            - echo Build started on `date`
            - echo Building the Docker image...
            - docker build -t $BIG3_API_REPO_NAME:$BIG3_API_IMAGE_TAG .
            - docker tag $BIG3_API_REPO_NAME:$BIG3_API_IMAGE_TAG $MY_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$BIG3_API_REPO_NAME:$BIG3_API_IMAGE_TAG
    post_build:
        commands:
            - echo Build completed on `date`
            - echo Pushing the Docker image...
            - docker push $MY_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$BIG3_API_REPO_NAME:$BIG3_API_IMAGE_TAG
            - printf '{"ImageURI":"%s"}' $MY_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$BIG3_API_REPO_NAME:$BIG3_API_IMAGE_TAG > imageDetail.json
artifacts:
    files:
        - 'image*.json'
        - 'appspec-prod.yml'
        - 'taskdef-prod.json'
    secondary-artifacts:
        DefinitionArtifact:
            files:
                - appspec-prod.yaml
                - taskdef-prod.json
        ImageArtifact:
            files:
                - imageDetail.json